name: Run GPT-OSS 20B with Ollama

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Prompt to send to GPT-OSS'
        required: true
        default: 'Hello, how are you?'
        type: string

jobs:
  run-gpt-oss:
    # WARNING: Standard free runners have 16GB RAM - may not be enough for GPT-OSS 20B
    # This workflow will attempt to run but may fail due to memory constraints
    runs-on: ubuntu-latest # 4-vCPU, 16GB RAM (free tier)
    
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Check system resources
      run: |
        echo "=== System Information ==="
        free -h
        nproc
        df -h
        echo "=========================="
    
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        
    - name: Start Ollama service
      run: |
        # Start Ollama in background
        ollama serve &
        sleep 10
        
        # Verify Ollama is running
        curl -f http://localhost:11434/api/tags || (echo "Ollama failed to start" && exit 1)
        
    - name: Attempt to pull GPT-OSS 20B model (may fail due to memory)
      run: |
        echo "Attempting to pull GPT-OSS 20B model..."
        echo "WARNING: This may fail on free runners due to insufficient RAM"
        
        # Try to pull a smaller quantized version first
        ollama pull gpt-oss:7b 2>/dev/null || echo "7B model not available"
        
        # Attempt 20B model (will likely fail on free tier)
        ollama pull gpt-oss:20b || echo "20B model failed - insufficient memory"
        
    - name: Verify model installation
      run: |
        echo "Available models:"
        ollama list
        
    - name: Test GPT-OSS 20B
      run: |
        echo "Testing GPT-OSS 20B with prompt: ${{ github.event.inputs.prompt }}"
        
        # Run inference with the provided prompt
        ollama run gpt-oss:20b "${{ github.event.inputs.prompt }}"
        
    - name: Run performance benchmark
      run: |
        echo "Running simple benchmark..."
        time ollama run gpt-oss:20b "Explain quantum computing in one paragraph."
        
    - name: Memory usage after model load
      run: |
        echo "=== Memory Usage ==="
        free -h
        echo "=== Process Memory ==="
        ps aux --sort=-%mem | head -10
        
    - name: Cleanup
      if: always()
      run: |
        # Stop Ollama and clean up
        pkill ollama || true
        rm -rf ~/.ollama/models/* || true
